---
title: "Vignette 2"
output: github_document
---

```{r, include=FALSE}
#-Libraries-#
library(tidyverse)
library(knitr)
library(ggplot2)
library(ggthemes)
library(gridExtra)
library(jagsUI)

#-Functions-#
corr_eqn <- function(x,y, digits = 2) {
  corr_coef <- round(cor(x, y), digits = digits)
  paste(corr_coef)
}

gm_mean = function(x, na.rm=TRUE){
  exp(sum(log(x[x > 0]), na.rm=na.rm) / length(x))
}

#-Import data-#
file <- read.csv("../RawData/DSG_yearly_demography.csv", header = TRUE)

#-Clan size files-#
file$DSGclan.size[is.na(file$DSGclan.size)] <- file$clan.size[is.na(file$DSGclan.size)]
file$DSGclan.size.change[is.na(file$DSGclan.size.change)] <- file$clan.size.change[is.na(file$DSGclan.size.change)]

file <- file %>% filter(!(clan != "talek" & (year == "2008")))
file <- drop_na(file)
```

Vignette 2 Table S1. Correlations between growth rate and demographic rates in Talek West clan.
```{r, echo=FALSE}
#-Output-#
file %>% 
  filter(clan == 'talek') %>%
  select(DSGclan.size.change, cub.dob, cub.survival, sub.survival, adult.survival) %>%
  rename('Growth Rate' = DSGclan.size.change, 'Fecundity' = cub.dob, 'Cub Survival' = cub.survival,
       'Subadult Survival' = sub.survival, 'Adult Survival' = adult.survival) %>%
  cor() %>%
  round(., digits = 2) %>% 
  kable(., format = "markdown")
```

Vignette 2 Table S2. Correlations between growth rate and demographic rates in Mara Triangle clans.
```{r, echo=FALSE}
#-Output-#
file %>% 
  filter(clan != 'talek') %>%
  select(DSGclan.size.change, cub.dob, cub.survival, sub.survival, adult.survival) %>%
  rename('Growth Rate' = DSGclan.size.change, 'Fecundity' = cub.dob, 'Cub Survival' = cub.survival,
       'Subadult Survival' = sub.survival, 'Adult Survival' = adult.survival) %>%
  cor() %>%
  round(., digits = 2) %>% 
  kable(., format = "markdown")
```